### ISSUE TITLE
Support using individual npm modules

### ISSUE THREAD

**Issue by megawac** [megawac/lodash-modularize#5]
Makes the generated file change from importing `_.last = require('lodash/array/last')` to `_.last = require('lodash.last')`

Issue would be touching the `package.json` -- perhaps inform user to run `npm i --save lodash.last`?

Could be useful for to avoid issues like https://github.com/lodash/lodash/issues/1149

**Comment by megawac** [comment]
The goal here would be to allow users to have `lodash` as a dev dependency and have the exact modules they use as direct dependencies.

Thoughts @jdalton?

**Comment by jdalton** [comment]
I don't think the `#1149` example is a good one. That's a clear fail on the atom devs to tackle packaging 101.

**Comment by megawac** [comment]
I suppose a real solution for #1149 would be to build lodash's `index.js` from modules, yeah..?

<sub>...Probably a terrible idea :sleepy: ...</sub>

**Comment by jdalton** [comment]
> I suppose a real solution for #1149 would be to build lodash's

Naw they should just do what browserify/webpack do and crawl the used files excluding the rest.

**Comment by megawac** [comment]
Oh definitely, I'm just suggesting that if the index.js file was
dynamically imported modules it would be a smaller download (but run into
other issues) :)

**Comment by jdalton** [comment]
>  (but run into other issues) :)

Yeah, I'd hear it from the devs clocking `require` times for sure.

**Comment by megawac** [comment]
On second thought @jdalton, it may be interesting to create a build for node which uses `Object.defineProperties` to dynamically require methods

**Comment by jdalton** [comment]
> On second thought @jdalton, it may be interesting to create a build for node which uses `Object.defineProperties` to dynamically require methods

Interesting!

**Comment by megawac** [comment]
@jdalton besides couldn't this be a workaround to #1149? Consider

```json
{
    "devDependencies": {"lodash": "^3.0", "lodash-modularize": "^1.0"},
    "scripts": {
        "prepublish": "lodash-modularize src/**.js -o src/depends/lodash.js -u --use-npm-modules"
    }
}
```

Where it installs all the required npm modules to `dependencies` and makes the compiled file use the npm lodash modules

**Comment by jdalton** [comment]
Ya maybe. I think `lodash-modularize` needs a little gif or example of what it's doing. It's hard for me to grasp from the basic examples what it's actually doing.
